### ISSUE TITLE
Apple pay not working

### ISSUE THREAD

**Issue by araafat3** [moyasar/moyasar-flutter#27]
In some iPhone mobiles, Apple Pay has not appeared
When appears to have an issue id returns null

**Comment by Fghurayri** [comment]
Hello @araafat3 

Maybe this issue is related to this one? https://github.com/moyasar/moyasar-flutter/issues/25

If not, please ensure you are using the latest SDK version and using a real device in a [supported country](https://support.apple.com/en-us/102775)

If the issue is still persistent, please share the following information:

Dart Version
Flutter Version
iOS Version
Physical or Simulator device
The PaymentConfig object used to initialize the widget
