### ISSUE TITLE
The Apple Pay token is unprocessable.

### ISSUE THREAD

**Issue by araafat3** [moyasar/moyasar-flutter#33]
When using apple pay button give me error The Apple Pay token is unprocessable.

**Comment by MOHAMMEDadel12** [comment]
is This issue still exist ?

**Comment by ahoshaiyan** [comment]
Apple Pay token processing does not work on Simulator. You need an actual iOS device.

You also need to setup Apple Developer Account merchant ID and complete certificate setup by following this link:
https://docs.moyasar.com/apple-pay-using-developer-account

Please follow steps correctly in order to get it to work:
https://docs.moyasar.com/flutter-sdk
